import os
import re
import argparse
import networkx as nx
from networkx.readwrite import json_graph
import json
from .utils import \
    sanitize_filename


def dump_function_cfg(func, cfg):
    """
    正确遍历函数的所有基本块并按地址顺序输出汇编
    """
    result = []

    # 获取该函数的所有节点（基本块）
    '''
    function_nodes = sorted(
        (node for node in cfg.graph.nodes() if node.function_address == func.addr),
        key=lambda n: n.addr
    )'''

    for block in func.blocks:
        if block is None:
            continue

        # 输出块的汇编（使用 capstone）
        for insn in block.capstone.insns:
            result.append(f"{hex(insn.address)}:\t{insn.mnemonic}\t{insn.op_str}")

        # 可选：块之间加空行或注释，便于阅读
        result.append("")

    return "\n".join(result)
    
    
def decompile_to_c(fname, func, cfg, proj):
    out = [
        "/* ================================================================ */\n",
        "/* Auto-generated by asm_to_c.py                                    */\n",
        "/* Decompiler: angr (https://angr.io)                               */\n",
        "/* ================================================================ */\n\n",
        "#include <stdint.h>\n",
        "#include <stdbool.h>\n\n",
    ]
    
    out.append(f"/* {'-' * 60} */\n")
    out.append(f"/* Function : {fname}\n")
    out.append(f"   Address  : {func.addr:#010x}\n")
    out.append(f"   Size     : {func.size} bytes\n")
    out.append(f"   {'-' * 58} */\n\n")
    hasCode = False
        
    dec = proj.analyses.Decompiler(func, cfg=cfg.model)
    if dec.codegen and dec.codegen.text:
        out.append(dec.codegen.text.rstrip())
        out.append("\n")
        hasCode = True
    else:
        out.append(f"/* [警告] {fname}: 反编译未产生输出 */\n")
        for e in dec.errors:
          msg = e.format() if hasattr(e, "format") else str(e)
          out.append(f"/* {msg} */\n")
        
    return hasCode, "".join(out)
    
    
def call_graph(infilename, cfg):
    named_cg = nx.MultiDiGraph()
    cg = cfg.kb.functions.callgraph
    
    for addr in cg.nodes():
        f = cfg.kb.functions.get(addr)
        named_cg.add_node(f.name if f else hex(addr))

    for u, v, _ in cg.edges(data=True):
        fu = cfg.kb.functions.get(u)
        fv = cfg.kb.functions.get(v)
        named_cg.add_edge(
            fu.name if fu else hex(u),
            fv.name if fv else hex(v),
        )
    
    data = json_graph.node_link_data(named_cg)
    json.dump(data, open(infilename +".callgraph.json", "w"), indent=2)


def main(binary_path):
    import angr
    parser = argparse.ArgumentParser(description="反汇编exe")
    parser.add_argument("-f", type=str, help="文件名")
    parser.add_argument("-o", type=str, default="asm_output", help="输出目录")
    args = parser.parse_args()

    infilename = args.f
    OUTPUT_DIR = os.path.join(os.path.dirname(args.f), args.o)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print("正在加载二进制文件并生成 CFG（可能需要一些时间）...")
    proj = angr.Project(binary_path, auto_load_libs=False)

    # normalize=True 能让基本块更规整，推荐保留
    cfg = proj.analyses.CFGFast(normalize=True, 
        data_references=True,     # 尝试解析数据引用，可能发现更多代码
        force_complete_scan=True, # 强制对整个代码段进行完整线性扫描（能显著增加发现的函数数量）
        force_smart_scan=True,
        show_progressbar=True)

    print(f"共发现 {len(cfg.kb.functions)} 个函数，开始导出...")
    call_graph(infilename, cfg)
    
    for func_addr, func in cfg.kb.functions.items():
        func_name = func.name or f"sub_{func_addr:x}"
        func_name = sanitize_filename(func_name)

        file_path = os.path.join(OUTPUT_DIR, f"{func_name}.asm")
        
        c_file = file_path +".c"
        has_c, c_code = decompile_to_c(func_name, func, cfg, proj)
        if has_c:
          with open(c_file, "w", encoding="utf-8") as f:
            f.write(c_code)

        asm_text = dump_function_cfg(func, cfg)

        if not asm_text.strip():
            continue

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(f"; Function: {func_name}\n")
            f.write(f"; Address: {hex(func_addr)}\n")
            f.write(f"; Size: {func.size} bytes\n\n")
            f.write(asm_text)

        procs = f"{list(cfg.kb.functions.keys()).index(func_addr)} / {len(cfg.kb.functions)}"
        has_c_m = "编译C" if has_c else "反汇编C错误"
        print(f"已处理 {procs} 个函数... {func_name} / {func.size} bytes, {has_c_m}")

    print("所有函数 ASM 导出完成！")


if __name__ == "__main__":
    main(infilename)